log:
  level: debug
  disable_sentry: true

db:
  url: "postgres://token:password@db:5432/url_shortener?sslmode=disable"

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: serv1_svc
  service_port: 80
  
server:
  bind_addr: ":8000"
  mount_path: "/"
  base_url: "http://localhost:8000/"
