version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: token
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U token -d url_shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    user: root
    command: migrate up 
    environment:
      KV_VIPER_FILE: /config.yaml
    depends_on:
      db:
        condition: service_healthy

  url-shortener:
    build: .
    user: root
    command: run service
    ports:
      - "8000:8000"
    environment:
      KV_VIPER_FILE: /config.yaml
    depends_on:
      migrate:
        condition: service_completed_successfully
      db:
        condition: service_healthy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - url-shortener